# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/course_s3_hls_2cg/vivado/02_led_register/led_register.srcs/sources_1/bd/design_1/ip/design_1_led_register_0_2/design_1_led_register_0_2.xci
# IP: The module: 'design_1_led_register_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/course_s3_hls_2cg/vivado/02_led_register/led_register.srcs/sources_1/bd/design_1/ip/design_1_led_register_0_2/constraints/led_register_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_led_register_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: f:/course_s3_hls_2cg/vivado/02_led_register/led_register.srcs/sources_1/bd/design_1/ip/design_1_led_register_0_2/design_1_led_register_0_2.xci
# IP: The module: 'design_1_led_register_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/course_s3_hls_2cg/vivado/02_led_register/led_register.srcs/sources_1/bd/design_1/ip/design_1_led_register_0_2/constraints/led_register_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_led_register_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
